export const OFFICIAL_ACTIVITIES: { code: string; description: string }[] = [
  { code: "1", description: "DESSECAÇÃO" },
  { code: "10", description: "EPIs" },
  { code: "100", description: "AQUISIÇÕES DE EQUIPAMENTOS" },
  { code: "101", description: "COLETA DE RESIDUOS" },
  { code: "103", description: "ADUBO (MAP)" },
  { code: "104", description: "INSERTICIDA LARGATA" },
  { code: "105", description: "HERBICIDA QUEBRA LOMBO" },
  { code: "106", description: "AQUAGEL - FERTILIZANTE" },
  { code: "107", description: "ADUBO FOLIAR DE MÉDIA PRODUÇÃO" },
  { code: "108", description: "H. EXTRAS 100% - T. RURAL" },
  { code: "109", description: "H. EXTRAS 100% - OP. TRATOR IRRIGAÇÃO" },
  { code: "110", description: "REFLEXO DE H. EXTRA - IRRIGAÇÃO" },
  { code: "111", description: "DESPESAS COM C.C.A." },
  { code: "112", description: "H. EXTRAS 100% - MECANICOS" },
  { code: "115", description: "H. EXTRAS 100% - ELETRICISTA DE AUTO" },
  { code: "116", description: "H. EXTRAS 100% - CALDEREIRO" },
  { code: "117", description: "H. EXTRAS 100% - OP. COLHEDORA" },
  { code: "118", description: "H. EXTRAS 100% - OP. TRANSBORDO" },
  { code: "121", description: "H. EXTRAS 100% - MOTORISTA PESADO" },
  { code: "122", description: "REFLEXO DE H. EXTRA - C. MECANIZADA" },
  { code: "124", description: "H. EXTRAS 100% - SERRALHEIRO" },
  { code: "125", description: "REFLEXO DE H. EXTRA - OFICINA" },
  { code: "126", description: "H. EXTRAS 100% - MOT. COMBOISTA" },
  { code: "127", description: "H. EXTRAS 100% - BORRACHEIRO MOT." },
  { code: "128", description: "REFLEXO DE H. EXTRA - TRANSPORTE" },
  { code: "13", description: "PLANTADEIRA DE CANA" },
  { code: "130", description: "H. EXTRAS 50% - MOTORISTA PESADO" },
  { code: "131", description: "H. EXTRAS 100% - MOT. MUNCK" },
  { code: "132", description: "H. EXTRAS 100% - TRATOR LEVE" },
  { code: "133", description: "REFLEXO DE H. EXTRA - MECANIZAÇÃO" },
  { code: "134", description: "H. EXTRAS 100% - AUX. ADM" },
  { code: "135", description: "REFLEXO DE H. EXTRA - ADM" },
  { code: "137", description: "EMPRESTIMOS - CUSTEIO AGRICOLA" },
  { code: "138", description: "EMPRESTIMOS -CPR" },
  { code: "139", description: "EMPRESTIMOS - INVESTIMENTOS RENOVAÇÃO" },
  { code: "14", description: "HERBICIDA CATAÇÃO" },
  { code: "140", description: "CAPITAL DE GIRO" },
  { code: "141", description: "CAPITAL DE GIRO - PARTES RELACIONADAS" },
  { code: "143", description: "CDC/LEASING" },
  { code: "144", description: "DESPESAS BANCARIAS C/ CARTORIO" },
  { code: "145", description: "SERVIÇOS DE AGRONOMIA" },
  { code: "146", description: "SEGUROS DE CULTURAS AGRICOLAS" },
  { code: "15", description: "HERBICIDA RODAPÉ" },
  { code: "16", description: "INSETICIDA DIATREIA" },
  { code: "162", description: "HERCICIDA CORTADOR SOQUEIRA" },
  { code: "163", description: "CORTE DE CANA - TERCEIROS" },
  { code: "164", description: "CARREGAMENTO DE CANA MANUAL" },
  { code: "165", description: "TRATOR APOIO CARREG. MANUAL" },
  { code: "166", description: "CATA DE CANA MANUAL" },
  { code: "168", description: "PRE MATURADOR" },
  { code: "170", description: "ADUBO FOLIAR DE ALTA PRODUÇÃO" },
  { code: "171", description: "RESITÊNCIA A SECA" },
  { code: "173", description: "ADUBO FOLIAR" },
  { code: "174", description: "CDC/LEASING" },
  { code: "175", description: "ALUGUEL DE REPETIDORA" },
  { code: "176", description: "MICROGEO" },
  { code: "177", description: "ADUBO 17-08-23" },
  { code: "178", description: "CATAÇÃO QUIMICA" },
  { code: "179", description: "DESPESAS COM PNEUS" },
  { code: "18", description: "INSETICIDA CIGARRINHA" },
  { code: "181", description: "CORTE DE SEMENTES DE CANA" },
  { code: "182", description: "HORA EXTRA 100% - CABO" },
  { code: "184", description: "REFLEXO DE H. EXTRA - CABO" },
  { code: "187", description: "GRAXA" },
  { code: "188", description: "DEPRECIAÇÃO" },
  { code: "19", description: "FUNGICIDA" },
  { code: "192", description: "CABO DE GUIA" },
  { code: "193", description: "TRANSPORTE DE MATERIAIS" },
  { code: "194", description: "PROVISÕES" },
  { code: "195", description: "ADUBAÇÃO DE COBERTA" },
  { code: "196", description: "ICMS SUBSTITUIÇÃO" },
  { code: "197", description: "NITROGÊNIO" },
  { code: "198", description: "DESPESAS COM GTA" },
  { code: "199", description: "PRODUÇÃO COLHEITA MECANIZADA" },
  { code: "2", description: "HERBICIDA PRÉ PLANTIO" },
  { code: "20", description: "MATURADOR" },
  { code: "200", description: "SERVIÇO DE INTERNET" },
  { code: "201", description: "SEGUROS DIRETORIA" },
  { code: "202", description: "IPVA" },
  { code: "203", description: "ADUBO 08 30 10 +" },
  { code: "207", description: "ADUBO 13 00 29" },
  { code: "209", description: "ADUBO 16 05 20" },
  { code: "21", description: "APLICAÇÃO AEREA" },
  { code: "212", description: "SERVIÇOS DE TERCEIROS (TRANSP. PESSOAL)" },
  { code: "214", description: "EXAME DO TRABALHO" },
  { code: "216", description: "SERVIÇOS DE TERCEIRO (CARREG. CANA)" },
  { code: "219", description: "DESPESAS C/ SERVIÇOS DE TERCEIROS" },
  { code: "220", description: "DESPESAS C/ MATERIAIS E CONSUMO" },
  { code: "221", description: "DESPESAS C/ SEGUROS DE PATRIMONIO" },
  { code: "222", description: "DESPESAS C/ COMUNICAÇÃO E INFORMAÇÃO" },
  { code: "223", description: "DESPESAS C/ PRODUTOS E INSUMOS" },
  { code: "224", description: "DESPESAS C/ TRANSPORTES DE TERCEIROS" },
  { code: "225", description: "DESPESAS C/ ALUGUEIS E ARRENDAMENTOS" },
  { code: "227", description: "INSETICIDA CORTADOR SOQUEIRA" },
  { code: "228", description: "DESPESAS COMERCIAIS" },
  { code: "229", description: "DESPESAS LEGAIS - IMPOSTOS/TAXAS" },
  { code: "230", description: "DESPESAS C/ VIAGENS E HOSPEDAGENS" },
  { code: "231", description: "DESPESAS SOCIAIS (FI)" },
  { code: "232", description: "DESPESAS C/  MATÉRIA-PRIMA-INSUMOS" },
  { code: "233", description: "TRANSPORTE DE ANIMAIS" },
  { code: "234", description: "DESPESAS C/ VIAGENS ADM" },
  { code: "235", description: "APLICAÇÃO HERBICIDA EM PASTO" },
  { code: "236", description: "DESPESAS C/ LOCAÇÃO/ALUGUEL MÁQUNAS AGRI" },
  { code: "237", description: "DESPESAS C/ FUNCIONARIO" },
  { code: "238", description: "GRATIFICAÇÃO E ADICIONAIS LID. IRRIGAÇÃO" },
  { code: "239", description: "AUX. TRANSP. TRAB. RURAIS IRRIGAÇÃO" },
  { code: "24", description: "TRAB. RURAL IMPLANTAÇÃO DE PROJETO" },
  { code: "241", description: "AUX. TRANSP. T. RURAIS AVULSO -IRRIGAÇÃO" },
  { code: "243", description: "AJUDA DE CUSTO LIDERANÇA IRRIGAÇÃO" },
  { code: "244", description: "H. EXTRAS 100% - CONTROLE OFICINA - ADM" },
  { code: "245", description: "H. EXTRAS 100% - ELETRICISTA DE AUTA TEN" },
  { code: "246", description: "INSALUBRIDADE MEC. AUT." },
  { code: "247", description: "INSALUBRIDADE" },
  { code: "248", description: "DESP. ADIC. NOTURNO P/ OFICINA AGRIC." },
  { code: "249", description: "GRATIFICAÇÃO E ADICIONAIS BORRACHARIA" },
  { code: "25", description: "RECISÃO" },
  { code: "250", description: "PRODUÇÃO MECANIZAÇÃO" },
  { code: "251", description: "GRATIFICAÇÃO E ADICIONAIS MECANIZAÇÃO" },
  { code: "252", description: "AJUDA DE CUSTO TRATORES PESADOS" },
  { code: "253", description: "INSALUBRIDADE MECANIZAÇÃO" },
  { code: "254", description: "ADICIONAL NOTURNO TRATORES PESADOS" },
  { code: "255", description: "H. EXTRAS 100% - ADMINISTRAÇÃO IRRIGAÇÃO" },
  { code: "256", description: "ADICIONAL NOTURNO ADMINIST. IRRIGAÇÃO" },
  { code: "257", description: "GRATIFICAÇÃO E ADICIONAIS ADM CONT. AGRÍ" },
  { code: "258", description: "INSALUBRIDADE ADM CONTROLE AGRÍCOLA" },
  { code: "259", description: "ADICIONAL NOTURNO ADMINIST. CONT. AGRÍCO" },
  { code: "26", description: "ALUGUEL DE MAQUINAS" },
  { code: "260", description: "GRATIFICAÇÃO E ADICIONAIS COLHEIT MANUAL" },
  { code: "261", description: "AJUDA DE CUSTO DEP. PESSOAL" },
  { code: "262", description: "INSALUBRIDADE SUPRIMENTOS" },
  { code: "263", description: "H. EXTRAS 100% - SUPRIMENTOS" },
  { code: "264", description: "ADICIONAL NOTURNO PECUÁRIA" },
  { code: "265", description: "INSALUBRIDADE PECUÁRIA" },
  { code: "266", description: "EXPERIMENTOS" },
  { code: "267", description: "TOMBAMENTO DE CANA MANUAL" },
  { code: "268", description: "SERVIÇO MÃO DE OBRA TERCEIR. PLANTIO" },
  { code: "27", description: "CONSULTORIA" },
  { code: "271", description: "SERVIÇO MÃO DE OBRA TERCEIRIZADA" },
  { code: "273", description: "DRONE PARA CATAÇÃO QUÍMICA" },
  { code: "274", description: "TRANSPORTE DE CANA" },
  { code: "275", description: "UNIFORME (FARDAMENTO)" },
  { code: "276", description: "MATERIAIS DE USO EM ESCRITÓRIO" },
  { code: "277", description: "SEGURO MÁQUINAS AGRÍCOLA" },
  { code: "278", description: "SERVIÇOS DE RASTREAMENTO TRANSPORTE" },
  { code: "279", description: "ALUGUEL DE CASA (RESIDENCIAL)" },
  { code: "28", description: "DESPESAS COM MANUTENÇÃO" },
  { code: "280", description: "SERVIÇO DE AUDITORIA CONTABIL" },
  { code: "281", description: "LEVANTAMENTO GEOGRÁFICO" },
  { code: "283", description: "H. EXTRAS 50% - OP. COLHEDORA" },
  { code: "285", description: "INSS EMPRESA (20%)" },
  { code: "286", description: "INSS DESC. FUNCIONÁRIO" },
  { code: "287", description: "H. EXTRAS 50% - OP. TRANSBORDO" },
  { code: "288", description: "ADICIONAL NOTURNO" },
  { code: "292", description: "AUX. TRANSP. OP. TRANSBORDO" },
  { code: "293", description: "H. EXTRAS 50% - TRAB. RURAL" },
  { code: "295", description: "H. EXTRAS 50% - MECANICOS" },
  { code: "297", description: "H. EXTRAS 50% - OP. TRATOR IRRIGAÇÃO" },
  { code: "298", description: "GRATIFICAÇÃO E ADICIONAIS OFICINA E PCM" },
  { code: "299", description: "AUX. TRANSP. COORD. PCM" },
  { code: "30", description: "DESPESAS COM ENERGIA" },
  { code: "300", description: "AJUDA DE CUSTO" },
  { code: "301", description: "H. EXTRAS 100% - AUXILIAR MECANICO" },
  { code: "302", description: "H. EXTRAS 50% - AUXILIAR MECANICO" },
  { code: "303", description: "GRATIFICAÇÃO E ADICIONAIS IRRIGAÇÃO" },
  { code: "304", description: "HORA EXTRA 100%" },
  { code: "305", description: "HORA EXTRA 50%" },
  { code: "306", description: "GRATIFICAÇÃO E ADICIONAIS" },
  { code: "307", description: "H. EXTRAS 100%" },
  { code: "308", description: "H. EXTRAS 50%" },
  { code: "31", description: "DESPESAS C/ COMBUSTÍVEIS E LUBRIFICANTES" },
  { code: "310", description: "PERICULOSIDADE" },
  { code: "311", description: "H. EXTRAS 50% - SUPRIMENTOS" },
  { code: "312", description: "AUXÍLIO TRANSPORTE" },
  { code: "313", description: "AMETRINA" },
  { code: "315", description: "RECEITA COM VENDA DE CANA" },
  { code: "316", description: "Lascas de Madeira" },
  { code: "32", description: "TRANSPORTE DE SEMENTE" },
  { code: "320", description: "GESSO AGRICOLA MINERAL" },
  { code: "322", description: "CALCARIO PURO" },
  { code: "325", description: "HERBICIDA PRE AEREA" },
  { code: "327", description: "TRATORISTA TRAMPULO M" },
  { code: "328", description: "TRATORISTA TRAMPULO A" },
  { code: "33", description: "ARRENDAMENTOS" },
  { code: "331", description: "TRATORISTA TRATOS CULTURAIS" },
  { code: "333", description: "TRATORISTA ADUBAÇÃO" },
  { code: "334", description: "TRABALHADOR RURAL BOMBEIRO D" },
  { code: "336", description: "TRABALHADOR RURAL - MEC D" },
  { code: "338", description: "TRABALHADOR RURAL D.A" },
  { code: "339", description: "DSR - S/ HORAS EXTRAS" },
  { code: "34", description: "TRANSPORTE DE CANA MECAN." },
  { code: "340", description: "MOTORISTA O" },
  { code: "341", description: "AVALIAÇÃO DE RISCOS AMBIENTAIS" },
  { code: "343", description: "COORDENADOR DA CIA" },
  { code: "344", description: "SAI MINERAIS" },
  { code: "345", description: "TRATADOR K" },
  { code: "347", description: "APOIO AO SULCAMENTO" },
  { code: "35", description: "SEGURO DE TRANSPORTE" },
  { code: "350", description: "PLANTIO MANUAL" },
  { code: "352", description: "PACOTE UBIFOL" },
  { code: "353", description: "PÓS GERAL - TCS" },
  { code: "355", description: "PEFORMANCE" },
  { code: "356", description: "DURIVO/ VERIMARQ" },
  { code: "357", description: "DIATREA - TCS" },
  { code: "359", description: "PUGÃO" },
  { code: "36", description: "MATERIAL DE EXPEDIENTE" },
  { code: "362", description: "APLICAÇÃO AEREA - ADUBO FOLIAR" },
  { code: "363", description: "APLICAÇÃO AEREA  - MATURADOR" },
  { code: "364", description: "TALISMAN" },
  { code: "365", description: "TRANSPORTE DE FUNCIONARIO" },
  { code: "366", description: "MAQUINA DE SOLDA" },
  { code: "367", description: "SEGUROS DE MAQUINAS" },
  { code: "368", description: "INTERNET" },
  { code: "369", description: "TRABALHADOR RURAL - SULCAMENTO" },
  { code: "37", description: "TELEFONE" },
  { code: "370", description: "TRABALHADOR RURAL D.A - DOSADORES 3" },
  { code: "371", description: "TRABALHADOR RURAL D.A - CAPIM 3" },
  { code: "372", description: "TRABALHADOR RURAL D.A - DRONE 3" },
  { code: "373", description: "TRABALHADOR RURAL - CANA INTEIRA D" },
  { code: "374", description: "GERENTE ADM Z" },
  { code: "376", description: "AUXILIAR - ELETRICISTA AUTOMOTIVO 4" },
  { code: "377", description: "MECÂNICO BOX OFICINA T" },
  { code: "378", description: "TRAB. RURAL - LEVANTAMENTO DE PRAGAS D" },
  { code: "379", description: "TRAB. RURAL - CONTROLE DE QUALIDADE D" },
  { code: "38", description: "DESPESAS COM CARTORIO" },
  { code: "384", description: "OPERADOR DE DRONE" },
  { code: "389", description: "TRABALHADOR RURAL - BOMBEIRO D" },
  { code: "390", description: "TRABALHADOR RURAL - BOMBEIRO D" },
  { code: "391", description: "TRABALHADOR RURAL - B0MBEIRO D" },
  { code: "392", description: "CONSULTORIA LEANDRO" },
  { code: "393", description: "CONSULTORIA RANGEL" },
  { code: "394", description: "CONSULTORIA ORGANIZA-E" },
  { code: "4", description: "CULPINICIDA" },
  { code: "40", description: "MATERIAL DE LIMPEZA" },
  { code: "41", description: "MATERIAL DE COPA E COZINHA" },
  { code: "42", description: "ANALISE DE SOLO" },
  { code: "43", description: "CONSORCIOS" },
  { code: "45", description: "ALUGUEL DE SOFT-WARE" },
  { code: "46", description: "MEDICAMENTOS" },
  { code: "47", description: "VACINAS" },
  { code: "48", description: "SERVIÇOS DE TERCEIROS (REC. TUBOS/CONEX)" },
  { code: "49", description: "RAÇÃO ANIMAL" },
  { code: "5", description: "NEMATICIDA" },
  { code: "50", description: "SILO" },
  { code: "51", description: "SÊMEM" },
  { code: "52", description: "ORGANIZAÇÃO (LEILÃO)" },
  { code: "54", description: "INSTALAÇÃO E CONSERVAÇÃO" },
  { code: "56", description: "PRODUÇÕES DE EMBRIÕES" },
  { code: "57", description: "FOLHA AVULSA" },
  { code: "59", description: "SEMENTES" },
  { code: "6", description: "EXAMES MÉDICOS" },
  { code: "60", description: "LUBRIFICANTES" },
  { code: "62", description: "ADUBO 16-00-30" },
  { code: "66", description: "ALUGUEL DE RADIOS" },
  { code: "67", description: "AQUISIÇÕES DE VEICULOS" },
  { code: "68", description: "AMÔNIA" },
  { code: "69", description: "PARTICIPAÇÃO DE SAFRA" },
  { code: "7", description: "TRANSPORTE DE PESSOAL" },
  { code: "70", description: "CORTE DE CANA - USINA CORURIPE" },
  { code: "72", description: "DESPESAS COM LICENCIAMENTO, TAXAS E SEG." },
  { code: "73", description: "ALUGUEL DE IMPRESORAS" },
  { code: "74", description: "MATERIAL DE INFORMATICA" },
  { code: "75", description: "RASTREADORES" },
  { code: "76", description: "TOPOGRAFIA" },
  { code: "77", description: "DESPESAS COM ALIMENTAÇÃO" },
  { code: "78", description: "REVISÃO DE AR- CONDIONADO" },
  { code: "79", description: "REVISÃO DE RÁDIOS" },
  { code: "8", description: "FERRAMENTAS" },
  { code: "80", description: "ALUGUEL DE MAQUINAS PESADAS" },
  { code: "81", description: "HERBICIDA PRÉ DE SOCA" },
  { code: "82", description: "ENRAIZADOR (0,5L POTAMOL+1L KYMON PLUZ)" },
  { code: "86", description: "TRANSPORTE DE CANA MANUAL" },
  { code: "88", description: "COMPRAS (RAÇÕES, MAT. DE PICINAS E ETC)" },
  { code: "89", description: "DESPESAS COM CONSELHOS" },
  { code: "90", description: "IPTU" },
  { code: "91", description: "TAXA DE OCUPAÇÃO" },
  { code: "92", description: "PLANO DE SAÚDE" },
  { code: "94", description: "DESPESAS COM CARTÃO DE CRÉDITO" },
  { code: "95", description: "DESPESAS DE ÁGUA E ESGOTO" },
  { code: "96", description: "DESPESAS DE TV P/ ASSINATURA" },
  { code: "97", description: "DESPESAS MARINA SAQUAREMA" },
  { code: "98", description: "DESPESAS PESSOAIS (DIRETORIA)" },
  { code: "99", description: "MATERIAL DE USO E CONSUMO" },
];
