export const OFFICIAL_COST_OBJECTS: { code: string; description: string }[] = [
  { code: "1", description: "CANA DE AÇÚCAR" },
  { code: "2", description: "Formação de Lavoura" },
  { code: "3", description: "Preparo Solo" },
  { code: "4", description: "Demarc./Levantamto Topográfico - P.Solo" },
  { code: "5", description: "Desmatamto/Destoca/Enleiramento - P.Solo" },
  { code: "6", description: "Limpeza do Terreno - P.Solo" },
  { code: "7", description: "Sistematização /Terraplanagem" },
  { code: "8", description: "Drenagem - P.Solo" },
  { code: "9", description: "Construção/Conservação Estradas" },
  { code: "10", description: "Construção/Conservação Canais" },
  { code: "11", description: "Experimentos/C.Pragas/Levant" },
  { code: "12", description: "Aplicação de Herbicida - P.Solo" },
  { code: "13", description: "Grade Pesada - P.Solo" },
  { code: "16", description: "Aplicação de Torta - P.Solo" },
  { code: "17", description: "Aplicação de Corretivos - P.Solo" },
  { code: "18", description: "Adubação Verde - P.Solo" },
  { code: "19", description: "Subsolagem/Descompactação - P.Solo" },
  { code: "20", description: "Grade Intermediária - P.Solo" },
  { code: "22", description: "Grade Leve - P.Solo" },
  { code: "24", description: "Aração - P.Solo" },
  { code: "84", description: "Serviço Apoio Adm-C.Rec-P.Solo" },
  { code: "251", description: "Canteirização - Penta" },
  { code: "25", description: "Plantio" },
  { code: "26", description: "Sulcação - Plantio" },
  { code: "28", description: "Adubação Manual - Plantio" },
  { code: "29", description: "Adubação Mecânica - Plantio" },
  { code: "30", description: "Corte/Carregamento de sementes - Plantio" },
  { code: "31", description: "Distribuição de Sementes - Plantio" },
  { code: "32", description: "Aplicação de Herbicida - Plantio" },
  { code: "33", description: "Experimentos/C.Pragas/Levant - Plantio" },
  { code: "34", description: "Coberta - Plantio" },
  { code: "35", description: "Semeio - Mecanizado" },
  { code: "36", description: "Acabamento de Carreadores - Plantio" },
  { code: "37", description: "Aplicação de Corretivo - Plantio" },
  { code: "38", description: "Queima de Palha/Enleiramento - Plantio" },
  { code: "105", description: "Serviço Apoio Adm-C.Rec-PLANTIO" },
  { code: "144", description: "Transporte de Pessoal - Plantio" },
  { code: "27", description: "Retificação de Sulco - Plantio" },
  { code: "389", description: "Adubação Orgânica - Plantio" },
  { code: "39", description: "Tratos Culturais Cana Planta" },
  { code: "40", description: "Aplicação de Herbicida - TC.Planta" },
  { code: "41", description: "Aplicação de Inseticida - TC.Planta" },
  { code: "42", description: "Limpa/Arranca de Capim - TC.Planta" },
  { code: "43", description: "Cultivo - TC.Planta" },
  { code: "44", description: "Adubação Manual - TC.Planta" },
  { code: "45", description: "Adubação Mecânica - TC.Planta" },
  { code: "46", description: "Aplicação Maturador - TC.Planta" },
  { code: "269", description: "Aplicação de Fungicida - TC. Planta" },
  { code: "47", description: "Replantio de Cana Planta - TC.Planta" },
  { code: "270", description: "Aplicação de Nematicida" },
  { code: "48", description: "Rouging - TC.planta" },
  { code: "49", description: "Adubação Foliar - TC.Planta" },
  { code: "313", description: "Controle de Pragas e Doenças TC.Planta" },
  { code: "382", description: "Catação química com Drone TC. Plantar" },
  { code: "384", description: "Aplicação Biologica - TC.Planta" },
  { code: "109", description: "Serviço Apoio Adm-C.Rec-TC PANTA" },
  { code: "120", description: "Tratos Culturais Cana Soca" },
  { code: "50", description: "Tratos Culturais Cana Soca" },
  { code: "51", description: "Aplicação de Herbicida - TC.Soca" },
  { code: "52", description: "Aplicação de Inseticidas - TC.Soca" },
  { code: "53", description: "Cultivo Simples - TC.Soca" },
  { code: "54", description: "Aplicação de Fungicida - TC.Soca" },
  { code: "55", description: "Adubação Manual  - TC.Soca" },
  { code: "56", description: "Adubação Mecânica - TC.Soca" },
  { code: "57", description: "Limpa/Arranca de Capim - TC.Soca" },
  { code: "58", description: "Replanta de Cana - TC.Soca" },
  { code: "59", description: "Conserv/Manut.Estrada/Carreador-TC.Soca" },
  { code: "60", description: "Aplicação de Maturador - TC.Soca" },
  { code: "61", description: "Aplicação de Corretivo - TC.Soca" },
  { code: "62", description: "Adubação Foliar -  TC.Soca" },
  { code: "268", description: "Aplicação de Nematicida - TC. Soca" },
  { code: "218", description: "Transporte de Pessoal - TC.Soca" },
  { code: "297", description: "Aplicação Biologica - TC.Soca" },
  { code: "312", description: "Controle de Pragas e Doenças TC.Soca" },
  { code: "383", description: "Catação química com Drone TC. Soca" },
  { code: "110", description: "Serviço Apoio Adm-C.Rec- TC SOCA" },
  { code: "125", description: "Colheita p/Industrialização" },
  { code: "407", description: "Pré Colheita" },
  { code: "64", description: "Experimentos/C.Pragas/Levant -P.Colheita" },
  { code: "65", description: "Conserv./Man.Estrada/Carreador-P.Colheit" },
  { code: "67", description: "Queima Cana - P.Colheita" },
  { code: "121", description: "Serviço Apoio Adm-C.Rec-P. COLHEITA" },
  { code: "63", description: "Colheita de Cana Manual" },
  { code: "68", description: "Corte Cana Manual -C.Man" },
  { code: "69", description: "Carregamento Mecanico- C.Man" },
  { code: "70", description: "Transporte Cana Corte Manual- C.Man" },
  { code: "71", description: "Reboque Convencioal/Julieta- C.Man" },
  { code: "74", description: "Serviço Bituca/Engate/Desengate -C.Man" },
  { code: "72", description: "Serviço Apoio Adm-C.Rec- C. MANUAL" },
  { code: "75", description: "Colheita de Cana Mecanizada" },
  { code: "79", description: "Corte de Cana Mecanizada- C.Mec" },
  { code: "78", description: "Transporte Cana Corte Mecaniza-C.Mec" },
  { code: "82", description: "Transbordo - C.Mec" },
  { code: "66", description: "Aceiros - P.Colheita" },
  { code: "116", description: "Tratores de Transbordo" },
  { code: "119", description: "Colhedeiras de Cana" },
  { code: "108", description: "Transbordo" },
  { code: "85", description: "Serviço Apoio Adm-C.Rec- C.MEC" },
  { code: "266", description: "Oficina da Colheita Mecanizada" },
  { code: "106", description: "Caminhões Canavieiros" },
  { code: "107", description: "Reboque" },
  { code: "73", description: "Sistemas de Irrigação e Fertirrigação" },
  { code: "86", description: "Sistemas de Irrigação e Fertirrigação" },
  { code: "88", description: "Conservação de Canais/Adutoras/Valetas" },
  { code: "89", description: "Pivot Linear" },
  { code: "83", description: "Carretel" },
  { code: "87", description: "Asperção Convencional" },
  { code: "122", description: "Serviço Apoio Adm-C.Rec-FERTIRRIGAÇÃO" },
  { code: "98", description: "Adm. e Controle de Irrigação" },
  { code: "91", description: "Mecanização de Irrigação/Fert Irrigação" },
  { code: "128", description: "Equip. de Pivot Linear" },
  { code: "129", description: "Equip. Carretel" },
  { code: "132", description: "Casa de Bombas" },
  { code: "135", description: "Equip. Aspesor" },
  { code: "137", description: "Equip. Motores Bombas" },
  { code: "139", description: "Equip. Eletro Bombas" },
  { code: "76", description: "Colheita de Mudas" },
  { code: "289", description: "Colheita de Mudas Manual" },
  { code: "292", description: "Corte de Mudas Manual" },
  { code: "293", description: "Carregamento de Mudas - C.Manual" },
  { code: "294", description: "Transporte de Mudas - C.Manual" },
  { code: "301", description: "Serviço Apoio Adm-C.Rec- C. MUDAS" },
  { code: "283", description: "Matéria Prima" },
  { code: "182", description: "Matéria Prima" },
  { code: "183", description: "Materia Prima C.Fornecedor" },
  { code: "243", description: "Materia Prima Própria - Seguros e Taxas" },
  { code: "582", description: "PECUÁRIA" },
  { code: "583", description: "BOVINOS" },
  { code: "584", description: "Gado P.O." },
  { code: "585", description: "Cria - PO" },
  { code: "586", description: "Recria - PO" },
  { code: "588", description: "Engorda PO" },
  { code: "315", description: "Semi Confinamento PO" },
  { code: "587", description: "Confinamento - PO" },
  { code: "317", description: "Touros e Matrizes - PO" },
  { code: "590", description: "Inseminação Art. P/Tempo Fixo - PO" },
  { code: "591", description: "Produção de Embriões e Prenhezes - PO" },
  { code: "592", description: "Coleta e Produção de Sêmen - PO" },
  { code: "589", description: "Serviços Aux. de Gado P.O." },
  { code: "593", description: "Gado Cara Limpa" },
  { code: "594", description: "Cria - Gado C. Limpa" },
  { code: "80", description: "Recria - Gado C. Limpa" },
  { code: "81", description: "Confinamento - Gado C. Limpa" },
  { code: "318", description: "Engorda - Gado C. Limpa" },
  { code: "322", description: "Touros e Matrizes - C. Limpa" },
  { code: "324", description: "Serviços Aux. de Gado C. Limpa" },
  { code: "595", description: "OUTROS ANIMAIS" },
  { code: "596", description: "Equinos e Muares" },
  { code: "597", description: "Equinos e Muares" },
  { code: "350", description: "FORMAÇÃO DE PASTAGEM" },
  { code: "354", description: "Preparo de Solo - Plantio de Pastagem" },
  { code: "329", description: "Limpeza do Terreno - P. Pastagem" },
  { code: "330", description: "Aplicação de Herbicidas - P. Pastagem" },
  { code: "336", description: "Grade Intermediária - P. Pastagem" },
  { code: "347", description: "Grade Leve- P. Pastagem" },
  { code: "328", description: "Serviço Apoio P. Pastagem" },
  { code: "355", description: "Plantio de Pastagem" },
  { code: "356", description: "Distribuição de Sementes - P. Pastagem" },
  { code: "357", description: "Coberta- Plantio de Pastagem" },
  { code: "358", description: "Semeio - Plantio de Pastagem" },
  { code: "359", description: "Serviço Apoio Adm-C.Rec-P. Pastagem" },
  { code: "371", description: "CULTURA DE MILHO" },
  { code: "321", description: "Cultivo de Milho" },
  { code: "240", description: "Plantio de Milho" },
  { code: "319", description: "Tratos Culturais Silagem" },
  { code: "326", description: "Colheita de Milho" },
  { code: "655", description: "MANUTENÇÃO PECUARIA" },
  { code: "869", description: "Manutenção Geral - Pecuaria" },
  { code: "669", description: "Manutenção de Pastos" },
  { code: "670", description: "Manutenção de Cercas" },
  { code: "675", description: "Manutenção Estábulos" },
  { code: "676", description: "Manutenção Barracões" },
  { code: "288", description: "Plantio de Sabiá" },
  { code: "184", description: "ADMINISTRAÇÃO PECUARIA" },
  { code: "677", description: "Adm. e Controle - Pecuária" },
  { code: "678", description: "Adm. e Controle de Pecuária" },
  { code: "679", description: "Mão de Obra Rural - Pecuária" },
  { code: "337", description: "Tratores de Pneus Leves - Pecuaria" },
  { code: "185", description: "Parceiria Pecuária" },
  { code: "873", description: "Parceria Pecuária" },
  { code: "418", description: "PARCERIA  LJ E CB" },
  { code: "422", description: "Vendas de Gado Elite (Parceria CB)" },
  { code: "423", description: "Vendas de Gado Elite" },
  { code: "403", description: "Custos Gado Elite (Parceria CB)" },
  { code: "412", description: "Cria - Gado Elite (Parceria CB)" },
  { code: "414", description: "Recria - Gado Elite (Parceria CB)" },
  { code: "415", description: "Engorda - Gado Elite (Parceria CB)" },
  { code: "419", description: "Confinamento - Gado Elite (Parceria CB)" },
  { code: "420", description: "Touros e Matrizes - Gado Elite (Parceria CB)" },
  { code: "421", description: "Serviços Aux. de Gado Elite (Parceria CB)" },
  { code: "859", description: "AUXILIARES AGRÍCOLA" },
  { code: "92", description: "AUXILIARES AGRICOLA" },
  { code: "93", description: "Oficina Agrícola" },
  { code: "94", description: "Administração/Controle Oficina Agrícola" },
  { code: "95", description: "Oficina Mecânica Automotiva" },
  { code: "416", description: "Oficina Eletrica Automotiva" },
  { code: "417", description: "Calderaria Automotiva" },
  { code: "124", description: "Oficina Volante Automotiva" },
  { code: "349", description: "Serralharia Automotiva" },
  { code: "96", description: "Borracharia Aumototiva" },
  { code: "97", description: "Lavagem/Lubrificação - O.Agric." },
  { code: "99", description: "Comboios Automotivo" },
  { code: "123", description: "Serviço Apoio Adm-C.Recebido-O.Agric." },
  { code: "282", description: "Oficina Elétrica de Alta Tensão" },
  { code: "222", description: "Meloso" },
  { code: "100", description: "Transporte Agrícola" },
  { code: "101", description: "Administração/Contr. Transporte Agrícola" },
  { code: "102", description: "Automóveis e Utilitários" },
  { code: "103", description: "Caminhões de Apoio" },
  { code: "104", description: "Caminhões Bombeiro" },
  { code: "90", description: "Serviços Aux.Rec- Transporte" },
  { code: "140", description: "Implementos Rodoviarios" },
  { code: "141", description: "Motocicletas" },
  { code: "111", description: "Mecanização Agrícola" },
  { code: "112", description: "Administração/Contr. Máquinas Agrícolas" },
  { code: "113", description: "Carregadeiras de Cana" },
  { code: "114", description: "Tratores de Pneus Leves" },
  { code: "115", description: "Tratores de Pneus Médios" },
  { code: "181", description: "Tratores de Pneus Pesados" },
  { code: "117", description: "Máquinas Pesadas" },
  { code: "154", description: "Serviços Aux.Rec-Mecanização" },
  { code: "118", description: "Implementos Agrícola" },
  { code: "378", description: "Drone" },
  { code: "244", description: "Mecanização e Transporte Terceiros" },
  { code: "245", description: "Ônibus de Terceiros" },
  { code: "246", description: "Tratores de Terceiros" },
  { code: "247", description: "Carregadeiras de Terceiros" },
  { code: "248", description: "Maquinas Pesadas de Terceiros" },
  { code: "249", description: "Transporte de Terceiros" },
  { code: "901", description: "ADMINISTRAÇÃO AGRÍCOLA" },
  { code: "902", description: "Administração Agrícola" },
  { code: "903", description: "Controle Geral Agrícola" },
  { code: "130", description: "Administração/Controle Agrícola" },
  { code: "131", description: "Topografia" },
  { code: "392", description: "Bioestação" },
  { code: "904", description: "Departamento de Estudos Técnicos" },
  { code: "134", description: "Controle de Pragas e Doenças" },
  { code: "133", description: "Experimentações" },
  { code: "905", description: "Serviços Auxiliares de Mão de Obra Rural" },
  { code: "136", description: "Mão de Obra Ruricola" },
  { code: "142", description: "Mão de Obra Ruricola - Herbicida" },
  { code: "252", description: "Mão de Obra Ruricola - Plantio" },
  { code: "257", description: "Mão de Obra Ruricola - C. Sementes" },
  { code: "263", description: "Mão de Obra Ruricola - C. Manual" },
  { code: "145", description: "Administração Geral" },
  { code: "199", description: "Financeiro" },
  { code: "200", description: "Informática CPD" },
  { code: "201", description: "Contabilidade" },
  { code: "202", description: "Controle de Custos/Planejamento" },
  { code: "203", description: "Jurídico" },
  { code: "205", description: "Administração e Controle" },
  { code: "206", description: "Apoio Administrativo" },
  { code: "207", description: "Segurança Patrimonial" },
  { code: "14", description: "Serviços de Apoio" },
  { code: "276", description: "Nova Aravel" },
  { code: "277", description: "Palmas Veículos" },
  { code: "278", description: "Prismel Veículos" },
  { code: "280", description: "Diesel Distribuidora" },
  { code: "281", description: "Loterica LJ" },
  { code: "376", description: "Condominio Shopping Cinema" },
  { code: "381", description: "LJ Energia, Serviços e Locações" },
  { code: "387", description: "APP Locações e Serviços LTDA" },
  { code: "146", description: "Recursos Humanos" },
  { code: "209", description: "Departamento de Pessoal" },
  { code: "210", description: "Recrutamento/Seleção/Treinamento" },
  { code: "211", description: "Segurança no Trabalho" },
  { code: "212", description: "Medicina do Trabalho" },
  { code: "213", description: "Controle/Qualidade Total" },
  { code: "147", description: "Assistência Social" },
  { code: "215", description: "Assistência Médica e Odontológica" },
  { code: "216", description: "Assistência Educacional" },
  { code: "217", description: "Assistência Social" },
  { code: "314", description: "Refeitorio" },
  { code: "148", description: "Suprimentos" },
  { code: "220", description: "Compras" },
  { code: "221", description: "Almoxarifado" },
  { code: "906", description: "Parceiros Agrícolas" },
  { code: "907", description: "Parceiros Agrícola" },
  { code: "138", description: "Parceria Agrícola Cana" },
  { code: "149", description: "Comercial" },
  { code: "150", description: "Comercial" },
  { code: "224", description: "Administração Comercial" },
  { code: "225", description: "Faturamentos e Emprestimos (mutuos)" },
  { code: "267", description: "Faturamento a Base de troca" },
  { code: "151", description: "Diretoria" },
  { code: "152", description: "Despesas Dedutiveis" },
  { code: "881", description: "Luiz Jatobá Filho" },
  { code: "882", description: "Luiz Antonio de Moura Castro Jatobá" },
  { code: "883", description: "Luiz Otávio Vieira de Moura Castro Jatob" },
  { code: "153", description: "Despesas Indedutíveis" },
  { code: "885", description: "DP - Luiz Jatobá Filho" },
  { code: "886", description: "DP - Luiz Antonio de Moura Castro Jatobá" },
  { code: "887", description: "DP - Luiz Otávio Vieira de Moura Castro" },
  { code: "911", description: "DP -Marise Vieira de Moura Castro Jatoba" },
  { code: "912", description: "DP- Daisy de Moura Castro Jatoba" },
  { code: "155", description: "Diretoria Geral" },
  { code: "204", description: "Diretoria" },
  { code: "253", description: "RECEITAS / DESPESAS" },
  { code: "254", description: "Vendas de Produção Própria" },
  { code: "255", description: "Cana de Açúcar" },
  { code: "256", description: "Venda de Cana de Açúcar" },
  { code: "308", description: "Outras Vendas Agric." },
  { code: "265", description: "Pecuária" },
  { code: "717", description: "Vendas Bovinos" },
  { code: "718", description: "Vendas Equinos" },
  { code: "719", description: "Vendas Caprinos" },
  { code: "720", description: "Vendas Suinos" },
  { code: "721", description: "Vendas Ovinos" },
  { code: "722", description: "Vendas Muares" },
  { code: "723", description: "Outras Vendas Pec." },
  { code: "860", description: "Haras / Rodeio" },
  { code: "731", description: "Receita Competição / Exposição" },
  { code: "735", description: "Receita Rodeios" },
  { code: "272", description: "Revendas de Produtos" },
  { code: "273", description: "Revendas de Mercadorias" },
  { code: "274", description: "Vendas de Almoxarifado" },
  { code: "275", description: "Vendas de Imobilizado" },
  { code: "15", description: "Devolução de Vendas de Produção Própria" },
  { code: "21", description: "Cana de Açúcar" },
  { code: "279", description: "Devolução Cana de Açucar" },
  { code: "23", description: "Pecuária" },
  { code: "284", description: "Devolução Vendas Bovinos" },
  { code: "285", description: "Devolução Vendas Equinos" },
  { code: "286", description: "Devolução Vendas Caprinos" },
  { code: "287", description: "Devolução Vendas Suinos" },
  { code: "861", description: "Devolução Vendas Ovinos" },
  { code: "862", description: "Devolução Vendas Muares" },
  { code: "863", description: "Devolução Outras Vendas" },
  { code: "864", description: "Haras / Rodeios" },
  { code: "865", description: "Devolução Competição / Exposição" },
  { code: "866", description: "Devolução Rodeios" },
  { code: "126", description: "Devolução de Revendas de Produtos" },
  { code: "127", description: "Devolução Revendas Mercadorias" },
  { code: "290", description: "Devolução Vendas de Almoxarifados" },
  { code: "291", description: "Devolução Vendas do Ativo Imobilizado" },
  { code: "170", description: "Encargos s/ Vendas de Produção Própria" },
  { code: "192", description: "ICMS -               S/Faturamento" },
  { code: "295", description: "ICMS Cana de Açúcar" },
  { code: "296", description: "ICMS Pecuária" },
  { code: "394", description: "IBS Impostos bens e Serviços Cana" },
  { code: "396", description: "IBS Impostos bens e Serviços Pecuaria" },
  { code: "397", description: "CBS Contribuição bens e Serviços Cana" },
  { code: "398", description: "CBS Contribuição bens e Serviços Pecuaria" },
  { code: "346", description: "PIS  -               S/Faturamento" },
  { code: "302", description: "PIS Cana de Açúcar" },
  { code: "303", description: "PIS Pecuária" },
  { code: "348", description: "COFINS -               S/Faturamento" },
  { code: "309", description: "COFINS Cana de Açúcar" },
  { code: "310", description: "COFINS Pecuária" },
  { code: "351", description: "IPI -               S/Faturamento" },
  { code: "316", description: "IPI Cana de Açúcar" },
  { code: "867", description: "IPI Pecuária" },
  { code: "352", description: "INSS" },
  { code: "320", description: "INSS Faturamento" },
  { code: "353", description: "Encargos s/ Revendas de Produtos" },
  { code: "405", description: "ICMS -               S/Revenda" },
  { code: "323", description: "ICMS Vendas de Almoxarifados" },
  { code: "406", description: "PIS -               S/Revenda" },
  { code: "325", description: "PIS Vendas de Almoxarifados" },
  { code: "408", description: "COFINS-               S/Revenda" },
  { code: "327", description: "COFINS Vendas de Almoxarifados" },
  { code: "409", description: "Receitas/Despesas Financeiras" },
  { code: "410", description: "Receitas Financeiras" },
  { code: "331", description: "Descontos Recebidos" },
  { code: "332", description: "Juros Recebidos" },
  { code: "333", description: "Recuperação de Despesas" },
  { code: "334", description: "Resultado de Aplicações Financeiras" },
  { code: "335", description: "Receita Participação Societária" },
  { code: "307", description: "Recuperação de Despesas Diretoria" },
  { code: "411", description: "Despesas Financeiras" },
  { code: "338", description: "Juros Passivos" },
  { code: "339", description: "Juros Sobre Financiamentos" },
  { code: "340", description: "Despesas Tarifas/Comercializ. Bancarias" },
  { code: "341", description: "Despesas IOF" },
  { code: "342", description: "Despesas PMT" },
  { code: "250", description: "Despesas Com taxas e Cartorio" },
  { code: "304", description: "Despesas IRRF Aplicação" },
  { code: "305", description: "Variação Monetaria Passiva" },
  { code: "375", description: "Encargos de Transação Financeiras" },
  { code: "298", description: "Outras Receitas" },
  { code: "299", description: "Outras Receitas" },
  { code: "300", description: "Brindes e Bonificação" },
  { code: "379", description: "Outras Receitas" },
  { code: "311", description: "Liberação Principal" },
  { code: "372", description: "Outras Despesas" },
  { code: "373", description: "Despesas Comerciais" },
  { code: "374", description: "Despesas com comissoes Pecuaria" },
  { code: "391", description: "Despesas com comissoes Agricolas" },
  { code: "393", description: "Fretes sobre Vendas de Animais" },
  { code: "896", description: "INVESTIMENTOS" },
  { code: "897", description: "Obras em Andamento" },
  { code: "898", description: "Obras  Agricola" },
  { code: "262", description: "Obra - Reforma Almoxarifado" },
  { code: "385", description: "Bioestação - obra" },
  { code: "399", description: "Projeto Rancho Alegre" },
  { code: "400", description: "Irrigação - Extinção de Multas de excedente reativos" },
  { code: "401", description: "Projeto Pau Paraíba" },
  { code: "899", description: "Obras Pecuária" },
  { code: "878", description: "Obras em Andamento Y" },
  { code: "900", description: "Obras Administração" },
  { code: "231", description: "Obra - Reforma Escritorio Agricola" },
  { code: "306", description: "Obra - Construção de galpão - 1.1.1" },
  { code: "386", description: "Obra - Reforma de Refeitorio" },
  { code: "388", description: "Obra - Construção de galpão - 1.1.3" },
  { code: "390", description: "Obra - Construção de estrada" },
  { code: "377", description: "Outras Obras" },
  { code: "360", description: "ADMINISTRAÇÃO CENTRO DE SERVIÇOS" },
  { code: "361", description: "Administração Centro de Serviços" },
  { code: "362", description: "Centro de Serviços Compartilhado C.C.S" },
  { code: "363", description: "Administração - Corporativo de Serviços C.C.S" },
  { code: "364", description: "Financeiro - Corporativo de Serviços C.C.S" },
  { code: "365", description: "Contabilidade - Corporativo de Serviços C.C.S" },
  { code: "366", description: "Jurídico - Corporativo de Serviços C.C.S" },
  { code: "367", description: "Informática CPD - Corporativo de Serviços C.C.S" },
  { code: "368", description: "Recursos Humanos - Corporativo de Serviços C.C.S" },
  { code: "369", description: "Comercial - Corporativo de Serviços C.C.S" },
  { code: "370", description: "Compras - Corporativo de Serviços C.C.S" },
  { code: "402", description: "Transporte - Corporativo de Serviços C.C.S" },
  { code: "156", description: "CUSTOS A APROPRIAR" },
  { code: "157", description: "CUSTOS A APROPRIAR" },
  { code: "158", description: "CUSTOS A APROPRIAR - ENTRESSAFRA" },
  { code: "160", description: "ENTRESSAFRA COLHEITA P/INDUSTRIALIZAÇÃO" },
  { code: "161", description: "ENTRESSAFRA SISTEMA DE IRRIGAÇÃO" },
  { code: "162", description: "ENTRESSAFRA CAMINHOES CANAVIEIROS" },
  { code: "163", description: "ENTRESSAFRA TRANSP. REBOQUE" },
  { code: "164", description: "ENTRESSAFRA TRANSP. TRANSBORDO" },
  { code: "165", description: "ENTRESSAFRA TRANSP.IMPL.RODOVIARIOS" },
  { code: "166", description: "ENTRESSAFRA MECAN. TRATORES TRANSBORDO" },
  { code: "167", description: "ENTRESSAFRA MECAN. COLHEDOREAS DE CANA" },
  { code: "159", description: "CUSTOS A APROPRIAR= AMORTIZAÇOES" },
  { code: "168", description: "CST APROPRIRA AMORTIZAÇÃO LAVOURAS" },
  { code: "169", description: "CST AMORTIZAÇÃO PLANTIO" },
  { code: "171", description: "CST AMORTIZAÇÃO TRATOS SOCARIA" },
  { code: "172", description: "CST AMORTIZAÇÃO ENTRESSAFRA" },
  { code: "173", description: "CST AMORTIZ ENTRES.-COLHEITA DE CANA" },
  { code: "174", description: "CST AMORTIZ ENTRES.-SIST. FERITRRIGAÇÃO" },
  { code: "175", description: "CST AMORTIZ ENTRES.-CAMINHOES CANAVIEIRO" },
  { code: "176", description: "CST AMORTIZ ADM. AGRICOLA" },
  { code: "177", description: "CST AMORTIZ ENTRES.- TRANSBORDO" },
  { code: "178", description: "CST AMORTIZ ENTRES.- IMPL. RODOVIARIOS" },
  { code: "179", description: "CST AMORTIZ ENTRES. TRATORES TRANSBORDO" },
  { code: "180", description: "CST AMORT.ENTRES. COLHEDEIRAS DE CANA" },
  { code: "874", description: "CUSTO DE PRODUTOS E SERVIÇOS" },
  { code: "875", description: "Custo de Produtos AGRICOLAS" },
  { code: "190", description: "Custos Formação Lavoura" },
  { code: "191", description: "Custo Formação Preparo de Solo" },
  { code: "195", description: "Custo Formação Plantio" },
  { code: "226", description: "Custo Formação TC Planta" },
  { code: "876", description: "Custos de Tratos Cana Soca" },
  { code: "193", description: "Custos de Tratos Cana Soca" },
  { code: "194", description: "Custo Cana de Açúcar" },
  { code: "395", description: "Cana de Açúcar" },
  { code: "187", description: "Corte/Carreg/Transporte" },
  { code: "188", description: "Parceiros Agrícolas" },
  { code: "189", description: "Amortização /Exaustão /lavouras" },
  { code: "259", description: "Adm. Agrícola Geral" },
  { code: "186", description: "Cana de Açúcar" },
  { code: "413", description: "Cst Cana com /Plantio/Tratos do ano" },
  { code: "230", description: "Cana de Açúcar" },
  { code: "232", description: "Corte/Carreg/Transporte" },
  { code: "233", description: "Parceiros Agrícolas" },
  { code: "234", description: "CST Planto/Tratos do Ano" },
  { code: "260", description: "Adm. Agrícola / Ano" },
  { code: "235", description: "Cst Cana  com /Amortização CST Padráo" },
  { code: "236", description: "Cana de Açúcar" },
  { code: "237", description: "Corte/Carreg/Transporte" },
  { code: "238", description: "Parceiros Agrícolas" },
  { code: "239", description: "Amortização /Exaustão /lavouras" },
  { code: "261", description: "Adm. Agrícola / Amortização" },
  { code: "227", description: "CUSTOS DA PECUARIA" },
  { code: "228", description: "Custo Pecuária" },
  { code: "404", description: "Custos Bovinos" },
  { code: "868", description: "Haras / Rodeio" },
  { code: "490", description: "SALDOS" },
  { code: "491", description: "Saldos Pecuários" },
  { code: "492", description: "Saldos Pecuários" },
  { code: "493", description: "Saldo Cria" },
  { code: "494", description: "Saldo Recria" },
  { code: "495", description: "Saldo Engorda" },
  { code: "496", description: "Saldo Confinamento" },
  { code: "497", description: "Saldo Equinos Registrados" },
  { code: "498", description: "Saldo Equinos Comuns" },
  { code: "499", description: "Saldo Asininos e Muares" },
  { code: "500", description: "Saldo Ovinos e Caprinos" },
  { code: "501", description: "Saldo Suínos" },
  { code: "502", description: "Saldo Touros e Matrizes" },
  { code: "503", description: "Saldo Estação de Monta" },
  { code: "504", description: "Saldo Prod. Prenhezes" },
  { code: "505", description: "Saldo Prod. Col. Sêmen Pec." },
];
